/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-03 10:50:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.z03_005fedu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import jspexp.vo.*;
import javaexp.sql.*;
import jspexp.a13_database.*;
import jspexp.a13_database.vo.*;

public final class noticeBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("jspexp.a13_database.vo");
    _jspx_imports_packages.add("javaexp.sql");
    _jspx_imports_packages.add("jspexp.a13_database");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("jspexp.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>쌍용대학교</title>\r\n");
      out.write("<link href=\"img/ss.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("<link href=\"PJ_css/noticeNo1.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"PJ_css/input.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@9\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"http://code.jquery.com/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"flex-box1\">\r\n");
      out.write("				<div id=\"box1\">\r\n");
      out.write("					<div id=\"top-box1\">\r\n");
      out.write("						<span id=\"tob-box1-span\">쌍용대학교</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"top-box2\">\r\n");
      out.write("					<span id=\"tob-box2-span\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.proName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 교수</span>\r\n");
      out.write("               <span id=\"tob-box2-span\"><input type=\"button\" id=\"bt2\" value=\"로그아웃\" onclick=\"logout()\" /></span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"flex-box2\">\r\n");
      out.write("				<div id=\"flex-box2_box1\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<div id=\"nav-box\">\r\n");
      out.write("	                     <ul id=\"navi\">                   \r\n");
      out.write("	                        <li class=\"group\">\r\n");
      out.write("								<div class=\"title\">공지사항</div>\r\n");
      out.write("								<ul class=\"sub\">\r\n");
      out.write("									<li><a href=\"noticeNo1.jsp\">공지사항 조회</a></li>\r\n");
      out.write("								</ul>                       	\r\n");
      out.write("	                           <div class=\"title\">강의 관리</div>\r\n");
      out.write("	                           <ul class=\"sub\">\r\n");
      out.write("								  <li><a href=\"lectureadd.jsp\">강의 등록</a></li>\r\n");
      out.write("	                              <li><a href=\"lecturemodify.jsp\">강의 수정</a></li>\r\n");
      out.write("	                              <li><a href=\"lecturedelete.jsp\">강의 삭제</a></li>\r\n");
      out.write("	                              <li><a href=\"lecEval.jsp?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">강의평가 조회</a></li>\r\n");
      out.write("	                              <li><a href=\"lecplanadd.jsp\">강의계획서 관리</a></li>\r\n");
      out.write("	                           </ul>\r\n");
      out.write("	                        </li>\r\n");
      out.write("	                        <li class=\"group\">\r\n");
      out.write("	                           <div class=\"title\">성적 관리</div>\r\n");
      out.write("	                           <ul class=\"sub\">\r\n");
      out.write("	                              <li><a href=\"schStudent.jsp?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pro.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">성적 입력</a></li>\r\n");
      out.write("	                           </ul>\r\n");
      out.write("	                        </li>\r\n");
      out.write("	                        <li class=\"group\">\r\n");
      out.write("	                           <div class=\"title\">학생관리</div>\r\n");
      out.write("	                           <ul class=\"sub\">\r\n");
      out.write("	                              <li><a href=\"search.jsp\">학생 조회</a></li>\r\n");
      out.write("	                              <li><a href=\"sendemail.jsp\">이메일 발송</a></li>\r\n");
      out.write("	                              <li><a href=\"studentAt.jsp\">출결 관리</a></li>\r\n");
      out.write("	                           </ul>\r\n");
      out.write("	                        </li>\r\n");
      out.write("	                     </ul>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"flex-box2_box2\">\r\n");
      out.write("					<div class=\"main-box-flex\">\r\n");
      out.write("						<div id=\"main-box1\">\r\n");
      out.write("							<div id=\"main-box1-iteam\">\r\n");
      out.write("								<span class=\"span-margin\" id=\"span1\">공지사항 조회</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<span class=\"span-margin\">공지사항 > 공지사항 조회</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"main-box-flex\">\r\n");
      out.write("						<div id=\"main-box2\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<div id=\"search-div\">\r\n");
      out.write("									<form>\r\n");
      out.write("										<select name=\"condition\" id=\"input01\">\r\n");
      out.write("											<option value=\"title\">제목</option>\r\n");
      out.write("											<option value=\"contents\">내용</option>\r\n");
      out.write("											<option value=\"both\">제목+내용</option>\r\n");
      out.write("										</select>\r\n");
      out.write("										<input type=\"text\" name=\"search\" id=\"input02\" />\r\n");
      out.write("										<input type=\"submit\" value=\"검색\" id=\"btn01\">\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"table-div\">\r\n");
      out.write("									");

									String title = "";
									String contents = "";
									String condition = request.getParameter("condition");
									if (condition == null)
										condition = "";
									if (condition.equals("title")) {
										title = request.getParameter("search");
									} else if (condition.equals("contents")) {
										contents = request.getParameter("search");
									} else if (condition.equals("both")) {
										title = request.getParameter("search");
										contents = request.getParameter("search");
									}

									noticeDao dao = new noticeDao();
									noticeVO sch = new noticeVO(title, contents);
									
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									<table width=\"1400\">\r\n");
      out.write("										<col width=\"10px\">\r\n");
      out.write("										<col width=\"100px\">\r\n");
      out.write("										<col width=\"10px\">\r\n");
      out.write("										<col width=\"50px\">\r\n");
      out.write("										<col width=\"10px\">\r\n");
      out.write("										<thead>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>번호</th>\r\n");
      out.write("												<th>제목</th>\r\n");
      out.write("												<th>작성자</th>\r\n");
      out.write("												<th>등록일</th>\r\n");
      out.write("												<th>조회수</th>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</thead>\r\n");
      out.write("										<tbody>\r\n");
      out.write("											");

											for (noticeVO n : dao.getNotices(sch)) {
											
      out.write("\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>");
      out.print(n.getNoticeNo());
      out.write("</td>\r\n");
      out.write("												<td><a href=\"noticeNo3.jsp\"/>");
      out.print(n.getTitle());
      out.write("</td>\r\n");
      out.write("												<td>관리자</td>\r\n");
      out.write("												<td>");
      out.print(n.getNoticeDate());
      out.write("</td>\r\n");
      out.write("												<td>");
      out.print(n.getViews());
      out.write("</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											");

											}
											
      out.write("\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div></div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("		//모든 서브 메뉴 감추기\r\n");
      out.write("		$(\".sub\").css({\r\n");
      out.write("			display : \"none\"\r\n");
      out.write("		});\r\n");
      out.write("		//$(\".sub\").hide(); //위코드와 동일 \r\n");
      out.write("\r\n");
      out.write("		$(\".title\").click(function() {\r\n");
      out.write("			//일단 서브메뉴 다 가립니다.\r\n");
      out.write("			//$(\".sub\").css({display:\"none\"});\r\n");
      out.write("\r\n");
      out.write("			//열린 서브메뉴에 대해서만 가립니다.\r\n");
      out.write("			$(\".sub\").each(function() {\r\n");
      out.write("				if ($(this).css(\"display\") == \"block\") {\r\n");
      out.write("					//$(\".sub\").css({display:\"none\"});\r\n");
      out.write("					//$(this).hide();\r\n");
      out.write("					$(this).slideUp(\"fast\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			//현재 요소의 다음 요소를 보이게 합니다.\r\n");
      out.write("			//$(this).next(\"ul\").css({display:\"block\"});\r\n");
      out.write("			//$(this).next(\"ul\").show();\r\n");
      out.write("			$(this).next(\"ul\").slideDown(\"fast\");\r\n");
      out.write("\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	// 로그아웃\r\n");
      out.write(" 	function logout(){\r\n");
      out.write("		  Swal.fire({\r\n");
      out.write("			  title: '로그아웃하시겠습니까?',\r\n");
      out.write("			  icon: 'question',\r\n");
      out.write("			  showCancelButton: true, // cancel버튼 보이기. 기본은 원래 없음\r\n");
      out.write("			  confirmButtonColor: '#3085d6', // confrim 버튼 색깔 지정\r\n");
      out.write("			  cancelButtonColor: '#d33', // cancel 버튼 색깔 지정\r\n");
      out.write("			  confirmButtonText: '확인', // confirm 버튼 텍스트 지정\r\n");
      out.write("			  cancelButtonText: '취소' // cancel 버튼 텍스트 지정\r\n");
      out.write("			}).then((result) => {\r\n");
      out.write("			  if (result.value) {\r\n");
      out.write("				//\"확인\" 버튼을 눌렀을 때 작업할 내용\r\n");
      out.write("				  location.href=\"n\"\r\n");
      out.write("			  }\r\n");
      out.write("			})\r\n");
      out.write("     }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
