/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-03 05:49:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.z03_005fedu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import jspexp.vo.*;
import javaexp.sql.*;
import jspexp.a13_database.*;
import jspexp.a13_database.vo.*;

public final class 연습_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("jspexp.a13_database.vo");
    _jspx_imports_packages.add("javaexp.sql");
    _jspx_imports_packages.add("jspexp.a13_database");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("jspexp.vo");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>쌍용 대학교</title>\r\n");
      out.write("<link href=\"main.css\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("   src=\"http://code.jquery.com/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("@import url(a00_main.css);  \r\n");
      out.write("\r\n");
      out.write("#addtable{\r\n");
      out.write("margin-top:5%;\r\n");
      out.write("margin-left: 40%;\r\n");
      out.write("font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("#bt{\r\n");
      out.write("margin-top:3%;\r\n");
      out.write("margin-left: 50%;\r\n");
      out.write("width:57px; height:33px;\r\n");
      out.write("border-radius:4px; \r\n");
      out.write("background:#0066CC;\r\n");
      out.write("color:white;\r\n");
      out.write("border:1px solid gray;\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("#bt2{\r\n");
      out.write("font-size: 15px;\r\n");
      out.write("border-radius:4px; \r\n");
      out.write("background:#0066CC;\r\n");
      out.write("color:white;\r\n");
      out.write("border:1px solid gray;\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bt3{\r\n");
      out.write("margin-left: 50%;\r\n");
      out.write("border-radius:4px; \r\n");
      out.write("background:#0066CC;\r\n");
      out.write("color:white;\r\n");
      out.write("border:1px solid gray;\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#center{\r\n");
      out.write("margin-top:5%;\r\n");
      out.write("margin-left:45%;\r\n");
      out.write("font-size:15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("   <div>\r\n");
      out.write("      <div>\r\n");
      out.write("         <div class=\"flex-box1\">\r\n");
      out.write("            <div id=\"box1\">\r\n");
      out.write("               <div id=\"top-box1\">\r\n");
      out.write("                  <span id=\"tob-box1-span\">쌍용대학교</span>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"top-box2\">\r\n");
      out.write("               <span id=\"tob-box2-span\">ID ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("교수</span>\r\n");
      out.write("               <span id=\"tob-box2-span\"><input type=\"button\" id=\"bt2\" value=\"로그아웃\" onclick=\"logout()\" /></span>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("<div class=\"flex-box2\">\r\n");
      out.write("            <div id=\"flex-box2_box1\">\r\n");
      out.write("               <div>\r\n");
      out.write("                  <div id=\"nav-box\">\r\n");
      out.write("                     <ul id=\"navi\">\r\n");
      out.write("                        <li class=\"group\">\r\n");
      out.write("                           <div class=\"title\">공지사항</div>\r\n");
      out.write("                           <ul class=\"sub\">\r\n");
      out.write("                              <li><a href=\"#\">-공지게시판</a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"group\">\r\n");
      out.write("                           <div class=\"title\">강의관리</div>\r\n");
      out.write("                           <ul class=\"sub\">\r\n");
      out.write("                              <li><a href=\"lectureadd.jsp\">-강의 등록</a></li>\r\n");
      out.write("                              <li><a href=\"lecturemodify.jsp\">-강의 수정</a></li>\r\n");
      out.write("                              <li><a href=\"lecturedelete.jsp\">-강의 삭제</a></li>\r\n");
      out.write("                              <li><a href=\"lecplanadd.jsp\">-강의계획서 관리</a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"group\">\r\n");
      out.write("                           <div class=\"title\">학생관리</div>\r\n");
      out.write("                           <ul class=\"sub\">\r\n");
      out.write("                              <li><a href=\"search.jsp\">-학생 조회</a></li>\r\n");
      out.write("                              <li><a href=\"sendemail.jsp\">-이메일 발송</a></li>\r\n");
      out.write("                              <li><a href=\"studentAt.jsp\">-출결 관리</a></li>\r\n");
      out.write("                           </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"flex-box2_box2\">\r\n");
      out.write("               <div class=\"main-box-flex\">\r\n");
      out.write("                  <div id=\"main-box1\">\r\n");
      out.write("                     <div id=\"main-box1-iteam\">\r\n");
      out.write("                        <span class=\"span-margin\" id=\"span1\">강의계획서등록/수정</span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div>\r\n");
      out.write("                        <span class=\"span-margin\">강의관리 > 강의계획서등록/수정</span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"main-box-flex\">\r\n");
      out.write("                  <div id=\"main-box2\">\r\n");
      out.write("                     <div>\r\n");
      out.write("                     ");
      out.write("\r\n");
      out.write("					<form action=\"lecplanupload.jsp\" method=\"post\" \r\n");
      out.write("						enctype=\"multipart/form-data\" id=\"center\"><br><br>\r\n");
      out.write("						강의명<input type=\"text\" name=\"lecName\" placeholder=\"등록할 강의명\"/><br><br>\r\n");
      out.write("						파일　<input type=\"file\" name=\"lecPlan\"/><br><br>\r\n");
      out.write("						<input type=\"button\" id=\"bt3\" value=\"등록 및 수정\" onclick=\"ckValid()\"/><br>\r\n");
      out.write("					</form>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div></div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("      //모든 서브 메뉴 감추기\r\n");
      out.write("      $(\".sub\").css({\r\n");
      out.write("         display : \"none\"\r\n");
      out.write("      });\r\n");
      out.write("      //$(\".sub\").hide(); //위코드와 동일 \r\n");
      out.write("\r\n");
      out.write("      $(\".title\").click(function() {\r\n");
      out.write("         //일단 서브메뉴 다 가립니다.\r\n");
      out.write("         //$(\".sub\").css({display:\"none\"});\r\n");
      out.write("\r\n");
      out.write("         //열린 서브메뉴에 대해서만 가립니다.\r\n");
      out.write("         $(\".sub\").each(function() {\r\n");
      out.write("            console.log($(this).css(\"display\"));\r\n");
      out.write("            if ($(this).css(\"display\") == \"block\") {\r\n");
      out.write("               //$(\".sub\").css({display:\"none\"});\r\n");
      out.write("               //$(this).hide();\r\n");
      out.write("               $(this).slideUp(\"fast\");\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("         //현재 요소의 다음 요소를 보이게 합니다.\r\n");
      out.write("         //$(this).next(\"ul\").css({display:\"block\"});\r\n");
      out.write("         //$(this).next(\"ul\").show();\r\n");
      out.write("         $(this).next(\"ul\").slideDown(\"fast\");\r\n");
      out.write("\r\n");
      out.write("      })\r\n");
      out.write("   });\r\n");
      out.write("   function logout(){\r\n");
      out.write("	      if(confirm(\"로그아웃하시겠습니까?\")){\r\n");
      out.write("	         location.href=\"a01_login_DB.jsp\"\r\n");
      out.write("	      }\r\n");
      out.write("	   }\r\n");
      out.write(" \r\n");
      out.write("	function ckValid(){\r\n");
      out.write("		   var lecName= document.querySelector(\"[name=lecName]\")\r\n");
      out.write("		   var lecNameV = lecName.value.trim();\r\n");
      out.write("		   var lecPlan = document.querySelector(\"[name=lecPlan]\")\r\n");
      out.write("		   var lecPlanV = lecPlan.value.trim();\r\n");
      out.write("		\r\n");
      out.write("		   if(lecNameV==\"\"){\r\n");
      out.write("		      alert(\"강의명을 입력해주세요.\")\r\n");
      out.write("		      lecName.focus()\r\n");
      out.write("		      return;\r\n");
      out.write("		   }\r\n");
      out.write("		   if(lecPlanV==\"\"){\r\n");
      out.write("			      alert(\"강의계획서를 첨부해주세요.\")\r\n");
      out.write("			      lecPlan.focus()\r\n");
      out.write("			      return;\r\n");
      out.write("			   }\r\n");
      out.write("		   document.querySelector(\"form\").submit();\r\n");
      out.write("		}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
