/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-02-02 05:05:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.z01_005foliveyoung;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<style>\r\n");
      out.write("#loginbox{\r\n");
      out.write("border: 1px solid #999999; \r\n");
      out.write("margin-left:\"40%\";\r\n");
      out.write("}\r\n");
      out.write("#red{\r\n");
      out.write("color:#dc3545;\r\n");
      out.write("background:lightgray;\r\n");
      out.write("}\r\n");
      out.write("#gray{\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("background:lightgray;\r\n");
      out.write("}\r\n");
      out.write("#etc{\r\n");
      out.write("color:gray;\r\n");
      out.write("font-size: 10pt;\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("#cancelbtn{\r\n");
      out.write("  border: 1px solid #A6CD48;\r\n");
      out.write("  background-color:#FFFFFF;\r\n");
      out.write("  height:30px;\r\n");
      out.write("  width:100px;\r\n");
      out.write("  margin:5px;\r\n");
      out.write("}\r\n");
      out.write("#joinbtn{\r\n");
      out.write("  color:#FFFFFF;\r\n");
      out.write("  border: 1px solid #A6CD48;\r\n");
      out.write("  background-color:#A6CD48;\r\n");
      out.write("  height:30px;\r\n");
      out.write("  width:100px;\r\n");
      out.write("  margin:5px;\r\n");
      out.write("}\r\n");
      out.write("table {\r\n");
      out.write("  border: 1px solid #A6CD48;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <fmt:requestEncoding value=\"utf-8\"/>     \r\n");
      out.write("    <title>올리브영</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row align-items-center py-3 px-xl-5\">\r\n");
      out.write("            <div class=\"col-lg-4 d-none d-lg-block\">\r\n");
      out.write("                <a href=\"\" class=\"text-decoration-none\">\r\n");
      out.write("                  　<img style=\"width:80%\" src=\"img/main.png\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-5 col-8 text-left\">\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Search for products\">\r\n");
      out.write("                        <div class=\"input-group-append\">\r\n");
      out.write("                            <span class=\"input-group-text bg-transparent text-primary\">\r\n");
      out.write("                                <i class=\"fa fa-search\"></i>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"margin-left:150px;\" class=\"col-lg-4 col-4\">\r\n");
      out.write("               <a class=\"text-dark\" href=\"\">회원가입</a>\r\n");
      out.write("               <span class=\"text-muted px-2\">|</span>\r\n");
      out.write("               <a class=\"text-dark\" href=\"\">로그인</a>\r\n");
      out.write("               <span class=\"text-muted px-2\">|</span>\r\n");
      out.write("               <a class=\"text-dark\" href=\"\">고객센터</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <div style=\"margin-top:30px\" class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row border-top px-xl-5\">\r\n");
      out.write("            <div class=\"col-lg-3 d-none d-lg-block\">\r\n");
      out.write("                <a class=\"btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100\" data-toggle=\"collapse\" href=\"#navbar-vertical\" style=\"height: 65px; margin-top: -1px; padding: 0 30px;\">\r\n");
      out.write("                    <h6 class=\"m-0\"><b>카테고리</b></h6>\r\n");
      out.write("                    <i class=\"fa fa-angle-down text-dark\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <nav class=\"collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light\" id=\"navbar-vertical\" style=\"width: calc(100% - 30px); z-index: 1;\">\r\n");
      out.write("                    <div class=\"navbar-nav w-100 overflow-hidden\" style=\"height: 410px\">\r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link\" data-toggle=\"dropdown\">기초화장품 <i class=\"fa fa-angle-down float-right mt-1\"></i></a>\r\n");
      out.write("                            <div class=\"dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0\">\r\n");
      out.write("                                <a href=\"\" class=\"dropdown-item\">스킨케어</a>\r\n");
      out.write("                                <a href=\"\" class=\"dropdown-item\">마스크팩</a>\r\n");
      out.write("                                <a href=\"\" class=\"dropdown-item\">클렌징</a>\r\n");
      out.write("                                <a href=\"\" class=\"dropdown-item\">선케어</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">더모코스메틱</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">메이크업/네일</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">바디케어</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">헤어케어</a>\r\n");
      out.write("                        <a href=\"\" class=\"nav-item nav-link\">향수/디퓨저</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("                <div class=\"col-lg-9\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0\">\r\n");
      out.write("                    <a href=\"\" class=\"text-decoration-none d-block d-lg-none\">\r\n");
      out.write("                        <h1 class=\"m-0 display-5 font-weight-semi-bold\"><span class=\"text-primary font-weight-bold border px-3 mr-1\">E</span>Shopper</h1>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\r\n");
      out.write("                        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse justify-content-between\" id=\"navbarCollapse\">\r\n");
      out.write("                        <div class=\"navbar-nav mr-auto py-0\">\r\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\"><b>오특</b></a>\r\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\"><b>신상</b></a>\r\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\"><b>랭킹</b></a>\r\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\"><b>프리미엄관</b></a>\r\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\"><b>기획전</b></a>\r\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\"><b>세일</b></a>\r\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\"><b>기프트카드</b></a>\r\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\"><b>멤버쉽/쿠폰</b></a>\r\n");
      out.write("                            <a href=\"index.html\" class=\"nav-item nav-link\"><b>이벤트</b></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Login Start -->\r\n");
      out.write("    <br><br><br><br><br>\r\n");
      out.write("    <h3 style=\"margin-left:50%;\">회원가입</h3>\r\n");
      out.write("    <h4 style=\"margin-left:20%;\">기본정보</h4>\r\n");
      out.write("    <span style=\"margin-left:67%;\" id=\"red\">⩗</span>표시는 필수 입력 항목입니다.\r\n");
      out.write("    <br>\r\n");
      out.write("    <div class=\"input-group\">\r\n");
      out.write("    <table style=\"margin-left:20%; width:60%;\">\r\n");
      out.write("    <tr><td id=\"red\">⩗　</td><td id=\"gray\">이름</td><td colspan=\"2\"><input type=\"text\" name=\"name\"></td></tr>\r\n");
      out.write("    <tr><td id=\"red\">⩗　</td><td id=\"gray\">아이디</td><td colspan=\"2\"><input type=\"text\" name=\"name\"><button id=\"joinbtn\">중복확인</button></td></tr>\r\n");
      out.write("    <tr><td id=\"red\">⩗　</td><td id=\"gray\">비밀번호</td><td colspan=\"2\"><input type=\"text\" name=\"name\">\r\n");
      out.write("    <a id=\"etc\"><br>영문자,숫자,특수문자 조합하여 8-12자리, 아이디와 4자리이상 동일, 반복 문자숫자 불가<br>사용가능 특수 문자:!\"#$%&'()*+,-./:;<=>?@^-'{|}~</a></td></tr>\r\n");
      out.write("    <tr><td id=\"red\">⩗　</td><td id=\"gray\">비밀번호 확인</td><td colspan=\"2\"><input type=\"text\" name=\"name\"></td></tr>\r\n");
      out.write("    <tr><td id=\"red\">⩗　</td><td id=\"gray\">생년월일</td><td colspan=\"2\">\r\n");
      out.write("    <input type=\"date\" name=\"userBirth\" required=\"required\"/>\r\n");
      out.write("    <br><a id=\"etc\">설정하신 생일을 기준으로 15일 전 생일쿠폰이 발행됩니다.</a>\r\n");
      out.write("    </td></tr>\r\n");
      out.write("    <tr><td id=\"red\">⩗　</td><td id=\"gray\">휴대전화번호</td><td colspan=\"2\">\r\n");
      out.write("    <select>\r\n");
      out.write("     <option> 010 </option>\r\n");
      out.write("     <option> 011 </option>\r\n");
      out.write("     <option> 016 </option>\r\n");
      out.write("     <option> 018 </option>\r\n");
      out.write("    </select>\r\n");
      out.write("    <input type = \"text\" size = \"6\"/> - <input type = \"text\" size = \"6\"/>\r\n");
      out.write("    <br><a id=\"etc\">주문 및 배송,쿠폰,이벤트 정보 등을 제공받으실 수 있습니다.</a>\r\n");
      out.write("    </td></tr>\r\n");
      out.write("    <tr><td id=\"red\">⩗　</td><td id=\"gray\">이메일</td><td colspan=\"2\">\r\n");
      out.write("    <input type = \"text\"/> @ <input type = \"text\"/> &nbsp;&nbsp;\r\n");
      out.write("    <select>\r\n");
      out.write("     <option> 직접입력 </option>\r\n");
      out.write("     <option> naver.com </option>\r\n");
      out.write("     <option> daum.net </option>\r\n");
      out.write("     <option> nate.com </option>\r\n");
      out.write("    </select>\r\n");
      out.write("    <br><a id=\"etc\">이메일 주소 입력 시 사용 가능 특수 문자:._</a>\r\n");
      out.write("    </td></tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    </div><br>\r\n");
      out.write("    <h4 style=\"margin-left:20%;\">선택정보</h4>\r\n");
      out.write("    <table style=\"margin-left:20%; width:60%;\">\r\n");
      out.write("    <tr><td id=\"gray\">　\r\n");
      out.write("    마케팅 채널<br>　수신 선택</td><td colspan=\"2\"><a id=\"etc\">포인트/이벤트/상품 소식을 전해드립니다.(공지목적의 발송되는 메일은 제외)</a><br>\r\n");
      out.write("        <input type = \"checkbox\" name = \"\"/>전체동의 <input type = \"checkbox\" name = \"\"/>이메일<input type = \"checkbox\" name = \"\"/>SMS<input type = \"checkbox\" name = \"\"/>휴대전화\r\n");
      out.write("\r\n");
      out.write("    </td></tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("    <button style=\"margin-left:45%;\" id=\"cancelbtn\">취소</button>\r\n");
      out.write("    <button id=\"joinbtn\">등록</button>\r\n");
      out.write("	<br><br><br><br><br>\r\n");
      out.write("    <!-- Login End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendor Start -->\r\n");
      out.write("        <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"row px-xl-5\">\r\n");
      out.write("            <div class=\"col\">\r\n");
      out.write("                <div class=\"owl-carousel vendor-carousel\">\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-1.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-2.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-3.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-4.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-5.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-6.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-7.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"vendor-item border p-4\">\r\n");
      out.write("                        <img src=\"img/vendor-8.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Vendor End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary text-dark mt-5 pt-5\">\r\n");
      out.write("        <div class=\"row px-xl-5 pt-5\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5\">\r\n");
      out.write("                <a href=\"\" class=\"text-decoration-none\">\r\n");
      out.write("                    <h1 class=\"mb-4 display-5 font-weight-semi-bold\">\r\n");
      out.write("                    <img src=\"img/foot_logo.png\"></h1>\r\n");
      out.write("                </a>\r\n");
      out.write("          \r\n");
      out.write("                <p class=\"mb-2\">공지사항</p>\r\n");
      out.write("                <p class=\"mb-2\">고객센터이용안내</p>\r\n");
      out.write("                <p class=\"mb-2\">온라인몰 고객센터</p>\r\n");
      out.write("                <h1 class=\"mb-4 display-5 font-weight-semi-bold\">\r\n");
      out.write("                <p class=\"mb-4\">\r\n");
      out.write("                    <span class=\"text-primary font-weight-bold border px-3 mr-1\">1522-0882</span></p></h1>\r\n");
      out.write("                <p class=\"mb-2\">매장 고객센터</p>\r\n");
      out.write("                <h1 class=\"mb-4 display-5 font-weight-semi-bold\">\r\n");
      out.write("                <p class=\"mb-4\">\r\n");
      out.write("                    <span class=\"text-primary font-weight-bold border px-3 mr-1\">1577-4887</span></p></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-8 col-md-12\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 mb-5\">\r\n");
      out.write("                        <h5 class=\"font-weight-bold text-dark mb-4\">고객센터 운영<br>[평일09:00-18:00]</h5>\r\n");
      out.write("                        <div class=\"d-flex flex-column justify-content-start\">\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"index.html\">주말 및 공휴일은<br> 1:1문의하기를 이용해주세요</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"shop.html\">업무가 시작되면 바로 처리해드립니다.</a>\r\n");
      out.write("                            <button class=\"footbtn\">1:1문의하기</button>\r\n");
      out.write("                           <button class=\"footbtn\">자주하는 질문</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 mb-5\">\r\n");
      out.write("                        <h5 class=\"font-weight-bold text-dark mb-4\"></h5>\r\n");
      out.write("                        <div class=\"d-flex flex-column justify-content-start\">\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"index.html\"></a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"shop.html\"></a>\r\n");
      out.write("   \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 mb-5\">\r\n");
      out.write("                        <h5 class=\"font-weight-bold text-dark mb-4\">올리브영 모바일웹</h5>\r\n");
      out.write("                      <img src=\"img/qr.png\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row border-top border-light mx-xl-5 py-4\">\r\n");
      out.write("            <div class=\"col-md-6 px-xl-0\">\r\n");
      out.write("                <p class=\"mb-md-0 text-center text-md-left text-dark\">\r\n");
      out.write("                    &copy; <a class=\"text-dark font-weight-semi-bold\" href=\"#\">씨제이올리브영 주식회사</a>. \r\n");
      out.write("대표이사 : 구창근 | 사업자등록번호 : 809-81-01574\r\n");
      out.write("주소 : (04323) 서울특별시 용산구 한강대로 372, 24층\r\n");
      out.write("(동자동, KDB타워)\r\n");
      out.write("호스팅사업자 : CJ 올리브네트웍스\r\n");
      out.write("통신판매업신고번호 : 2019-서울용산-1428\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 px-xl-0 text-center text-md-right\">\r\n");
      out.write("                <img class=\"img-fluid\" src=\"img/payments.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-primary back-to-top\"><i class=\"fa fa-angle-double-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Contact Javascript File -->\r\n");
      out.write("    <script src=\"mail/jqBootstrapValidation.min.js\"></script>\r\n");
      out.write("    <script src=\"mail/contact.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
